# Generated by Django 4.2.7 on 2023-11-23 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='profile_pics')),
                ('occupation', models.CharField(blank=True, choices=[('student', 'Student'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('developer', 'Developer'), ('musician ', 'Musician')], max_length=255, null=True)),
                ('education', models.CharField(blank=True, choices=[('high school', 'High School'), ('college', 'College'), ('graduate school', 'Graduate School'), ('no education', 'No Formal education')], max_length=255, null=True)),
                ('interests', models.CharField(blank=True, choices=[('music', 'Music'), ('sports', 'Sports'), ('technology', 'Technology'), ('coding', 'Coding')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
